print("Hello, World!")
print("Waheed")
print("Waheed Ahmad")
print("1,2,3")
print("Hello\nWorld")
print("Hello\tWorld")
print("apple","banana","cherry",sep=",")
print(1,2,3,sep="-")
print("Hello",end=" ")
print("World")
print(1,end="")
print(2)
print("He said, \"Hello!\"")
print("This is a backslash :\\")
print("I am 21 years old")
print("The number is 5")
print(1)
print(2)
print(3)
print(4)
print(5)
